# Generated by Django 4.1 on 2024-11-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rag', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounting',
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
        migrations.DeleteModel(
            name='Params',
        ),
        migrations.DeleteModel(
            name='Taxes',
        ),
    ]
