# Generated by Django 4.1 on 2024-11-06 06:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rag', '0002_delete_accounting_delete_chathistory_delete_params_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemPromptGerman', models.TextField()),
                ('SystemPromptEnglish', models.TextField()),
                ('temperature', models.FloatField()),
                ('max_tokens', models.IntegerField(default=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.TextField()),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemPromptGerman', models.TextField()),
                ('SystemPromptEnglish', models.TextField()),
                ('temperature', models.FloatField()),
                ('max_tokens', models.IntegerField(default=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemPromptGerman', models.TextField()),
                ('SystemPromptEnglish', models.TextField()),
                ('temperature', models.FloatField()),
                ('max_tokens', models.IntegerField(default=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_user', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Rag.chatsession')),
            ],
        ),
    ]
