# Generated by Django 4.1 on 2024-11-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rag', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounting',
        ),
        migrations.DeleteModel(
            name='Taxes',
        ),
    ]
